--- #YAML:1.0
name:               WebService-TWFY-API
version:            0.04
abstract:           API interface for TheyWorkForYou.com
author:
    - Spiros Denaxas (s [dot] denaxas [@] gmail [dot]com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Request:    0
    HTTP::Response:   0
    LWP::UserAgent:   0
    Test::Exception:  0
    Test::More:       0
    URI:              0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
