---
abstract: 'API interface for TheyWorkForYou.com'
author:
  - 'Spiros Denaxas (s [dot] denaxas [@] gmail [dot]com)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-TWFY-API
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Request: 0
  Test::Exception: 0.24
  Test::Simple: 0.44
version: 0.06
